export const SAVE_TAB_AND_PANEL = 'app/ElegantMenu/SAVE_TAB_AND_PANEL';
export const SAVE_TAB_AND_PANEL_THEN_SWITCH_TAB = 'app/ElegantMenu/SAVE_TAB_AND_PANEL_THEN_SWITCH_TAB';
export const SAVE_TAB_AND_PANEL_SUCCESS = 'app/ElegantMenu/SAVE_TAB_AND_PANEL_SUCCESS';
export const SAVE_TAB_AND_PANEL_ERROR = 'app/ElegantMenu/SAVE_TAB_AND_PANEL_ERROR';

export const DELETE_TAB_AND_PANEL = 'app/ElegantMenu/SAVE_TAB_AND_PANEL';
export const DELETE_TAB_AND_PANEL_SUCCESS = 'app/ElegantMenu/SAVE_TAB_AND_PANEL_SUCCESS';
export const DELETE_TAB_AND_PANEL_ERROR = 'app/ElegantMenu/SAVE_TAB_AND_PANEL_ERROR';


export const SAVE_TAB = 'app/ElegantMenu/SAVE_TAB';
export const SAVE_TAB_SUCCESS = 'app/ElegantMenu/SAVE_TAB_SUCCESS';
export const SAVE_TAB_ERROR = 'app/ElegantMenu/SAVE_TAB_ERROR';

export const RESET_SAVED_SUCCESSFULLY = 'app/ElegantMenu/RESET_SAVED_SUCCESSFULLY';

export const TOGGLE_CATEGORY_SORT_MODE = 'app/ElegantMenu/TOGGLE_CATEGORY_SORT_MODE';
export const TOGGLE_CATEGORY_SORT_MODE_CONTROLLER = 'app/ElegantMenu/TOGGLE_CATEGORY_SORT_MODE_CONTROLLER';

export const MODIFY_TAB_AND_PANEL_DIRTINESS = 'app/ElegantMenu/MODIFY_TAB_AND_PANEL_DIRTINESS';
